as yet unclassified
wholeTextOnlyEmail
	^ 'Received: from mail-pa0-f47.google.com (unknown [209.85.220.47])
	by ip-10-39-136-77 (Postfix) with ESMTPS id 4190D2C00D7
	for <reply+ltqNJ7nJLw@reply.example.com>; Fri,  9 Jan 2015 23:50:17 +0000 (UTC)
Received: by mail-pa0-f47.google.com with SMTP id kq14so21246483pab.6
        for <reply+ltqNJ7nJLw@reply.example.com>; Fri, 09 Jan 2015 15:50:17 -0800 (PST)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20130820;
        h=x-gm-message-state:content-type:mime-version:subject:from
         :in-reply-to:date:content-transfer-encoding:message-id:references:to;
        bh=ctM5QfP+XewFCd4xvwlPUkhpEFV1g8/h63Br1jvL9VM=;
        b=k+Qk5U6DIuTCne8iSKpxz6iY4ns1aqxv0tpbHVp026S597lLaZZDN3XbmRwvNpPob/
         4FgTprRMFRVweTviddf3kZzzaPJLbRfO31jqHbFjqLtWtTCxTW86vLOitIvWNIhFJm2/
         8jBehTJQJsMjSFBIEV18rZBN8mGotEoUlTRz3Z2S+LMFMLh+XGOI4Sz/q7TFJDAOAXUH
         8UZksXWs9Y8J6WTGDelIIfpnQTlMn+OXGAhgCUd3qD5v9fk/gd0kyeh4zkyxHmHOPgPX
         muVOZluH0N/MtQ4KSlAxX0Uusw32V/hlkQyoGB3MYukGVYI7NCR4nVK7Rq7Rj0MyHiWh
         nsqw==
X-Gm-Message-State: ALoCoQk9ynuhhYKq7yFiOyPom5jCEpWXmdA8cRXut4QVyowCMRclz/56QZHYVwr2eEbQFPKTF0RC
X-Received: by 10.68.208.65 with SMTP id mc1mr27219986pbc.111.1420847416973;
        Fri, 09 Jan 2015 15:50:16 -0800 (PST)
Received: from [192.168.2.5] (c-76-105-165-219.hsd1.or.comcast.net. [76.105.165.219])
        by mx.google.com with ESMTPSA id j8sm802757pdo.79.2015.01.09.15.50.15
        for <reply+ltqNJ7nJLw@reply.example.com>
        (version=TLSv1 cipher=ECDHE-RSA-RC4-SHA bits=128/128);
        Fri, 09 Jan 2015 15:50:15 -0800 (PST)
Content-Type: text/plain; charset=us-ascii
Mime-Version: 1.0 (Mac OS X Mail 7.3 \(1878.6\))
Subject: Re: Paul [message] from Paul DeBruicker titled: "Does adding a comment via email work?"
From: Paul DeBruicker <paul@example.com>
In-Reply-To: <30215478.20150109232220.54b062aceb0b47.47114620@mail128-13.atl41.mandrillapp.com>
Date: Fri, 9 Jan 2015 15:50:13 -0800
Content-Transfer-Encoding: quoted-printable
Message-Id: <F16D9869-859A-4D79-B8FC-A800C0CE23DC@example.com>
References: <30215478.20150109232220.54b062aceb0b47.47114620@mail128-13.atl41.mandrillapp.com>
To: reply+ltqNJ7nJLw@reply.example.com
X-Mailer: Apple Mail (2.1878.6)

So the formatting needs help



What are you gonna do about that?





On Jan 9, 2015, at 3:22 PM,Customer support wrote =
<help@example.com> wrote:

>=20
> Hi Paul,
> Paul DeBruicker asked us to send you a message. It is below.
> Does adding a comment via email work?
>=20
> We will see!
>=20
> Thanks and I hope you have a good day.
> P.S. - Reply to this email and we will subscribe your to this message =
& add your reply as a comment. Leave your reply blank to just subscribe =
without commenting.
> Sent from=20
> Unsubscribe here
>=20


--
My Name
Founder
Company
cell: 555-555-5555
office: 800-555-5555
me@example.com
https://www.example.com'