as yet unclassified
wholeMultipartEmail
	^ 'Delivered-To: paul@example.com
Received: by 10.114.216.33 with SMTP id on1csp524570ldc;
        Fri, 9 Jan 2015 15:58:48 -0800 (PST)
X-Received: by 10.50.253.12 with SMTP id zw12mr5142801igc.24.1420847927646;
        Fri, 09 Jan 2015 15:58:47 -0800 (PST)
Return-Path: <support@mandrill.zendesk.com>
Received: from out07.pod1.ord.zdsys.com (out07.pod1.ord.zdsys.com. [50.57.4.208])
        by mx.google.com with ESMTPS id l81si7461115iod.48.2015.01.09.15.58.46
        for <paul@example.com>
        (version=TLSv1.1 cipher=ECDHE-RSA-RC4-SHA bits=128/128);
        Fri, 09 Jan 2015 15:58:47 -0800 (PST)
Received-SPF: pass (google.com: domain of support@mandrill.zendesk.com designates 50.57.4.208 as permitted sender) client-ip=50.57.4.208;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of support@mandrill.zendesk.com designates 50.57.4.208 as permitted sender) smtp.mail=support@mandrill.zendesk.com;
       dkim=pass header.i=@zendesk.com
Received: from zendesk.com (work08.pod1.ord.zdsys.com [192.168.100.144])
	by out07.pod1.ord.zdsys.com (Postfix) with ESMTP id D41EF21F41
	for <paul@example.com>; Fri,  9 Jan 2015 23:58:46 +0000 (UTC)
Date: Fri, 09 Jan 2015 23:58:46 +0000
From: Mandrill Support <help@mandrill.com>
Reply-To: Mandrill Support <help@mandrill.com>
To: Paul DeBruicker <paul@example.com>
Message-ID: <MTNPHCZJ_54b06b36abdfc_2a253f81690cd40425822b_sprut@zendesk.com>
In-Reply-To: <E5FE79A0-2957-4912-B8DD-3A1541FCC0F8@example.com>
References: <MTNPHCZJ@zendesk.com>
 <E5FE79A0-2957-4912-B8DD-3A1541FCC0F8@example.com>
Subject: Thanks for contacting Mandrill Support: Ticket 78906 created (Is
 there any way to prevent you from stripping line endings from inbound emails?)
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_54b06b36ce026_2a253f81690cd404258493";
 charset=utf-8
Content-Transfer-Encoding: 7bit
X-Auto-Response-Suppress: All
Auto-Submitted: auto-generated
X-Mailer: Zendesk Mailer
X-Delivery-Context: event-id-49925307333
DKIM-Signature:  v=1; a=rsa-sha256; c=relaxed/relaxed; d=zendesk.com;
 q=dns/txt; s=zendesk1; t=1420847926;
 bh=o9yyTcDwBfEN2Gvbtki9dhNLP5IRmz+4QqryiQtYwWg=;
 h=date:from:reply-to:to:message-id:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding;
 b=1q+2s+dUsE07vwQFNycalZDdUKoAMlRT97f9TFzcZU+4EZay9QAfYQD2hrDcWS+FywynhsxUxJZ9os9K8RkvhQaE3x/7J0LQxnDYdH4EMkcFl+S+6iCSp/K2ubaznd9Fd9ZdT9B2srR+mBmpGH0/4QvRd5sHp9ZShLrc3jZvMdw=


----==_mimepart_54b06b36ce026_2a253f81690cd404258493
Content-Type: text/plain;
 charset=utf-8
Content-Transfer-Encoding: quoted-printable

##- Please type your reply above this line -##

Thanks for contacting Mandrill Support: Ticket 78906 created (Is there an=
y way to prevent you from stripping line endings from inbound emails?)

<strong>We''ve received your request.</strong>
Your ticket number is 78906.


If you have a Mandrill account, <em>please ensure your username was inclu=
ded </em> along with <strong>detailed information</strong> about your req=
uest so we can respond as quickly as possible.


You can add additional comments by replying to this email.

In the meantime, search for common questions in our <a href=3D"http://hel=
p.mandrill.com">Knowledge Base</a>, check Mandrill''s <a href=3D"http://st=
atus.mandrillapp.com">server status</a>, or review our <a href=3D"https:/=
/mandrillapp.com/docs/">documentation</a>.

----------------------------------------------

Paul DeBruicker, Jan 09 06:58 PM

Hi - =



I''m trying to parse inbound emails to extract just the relevant parts of =
the reply.   With the default settings for Inbound, it seems that your so=
ftware is stripping out the line endings of the text body of the email.  =
Is that right, and if so is there a way to shut that off?


Thanks


Paul









[MTNP-HCZJ]=

----==_mimepart_54b06b36ce026_2a253f81690cd404258493
Content-Type: text/html;
 charset=utf-8
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://ww=
w.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3DUTF=
-8" />
</head>
<body style=3D"width: 100%!important; margin: 0; padding: 0;background-co=
lor:#f1f1f2;">
<center>
	<div style=3D"padding: 10px ; line-height: 18px; font-family: "Lucida S=
ans Unicode", "Lucida Grande", "Tahoma", Verdana, sans-serif; font-size: =
12px; color:#444444; text-align:center; background-color:#ffffff;">
	  ##- Please type your reply above this line -##
	</div>
<table border=3D"0" cellpadding=3D"0" cellspacing=3D"0" height=3D"100%" w=
idth=3D"100%" style=3D"border-collapse:collapse;margin:0;padding:0;backgr=
ound-color:#d0d2d3;min-height:100%;width:100%">
	<tbody>
		<tr> =

			<td align=3D"center" valign=3D"top" style=3D"border-collapse:collapse"=
>
				<table border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"100%=
" style=3D"border-collapse:collapse">
					<tbody>
						<tr>
							<td align=3D"center" valign=3D"top" style=3D"border-collapse:colla=
pse">
								<table border=3D"0" cellpadding=3D"2" cellspacing=3D"0" width=3D"=
100%" style=3D"border-collapse:collapse;background-color:#262527">
									<tbody>
										<tr>
											<td align=3D"center" valign=3D"top" style=3D"border-collapse:c=
ollapse">
												<table border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=
=3D"600" style=3D"border-collapse:collapse; max-width:600px;">
													<tbody>
														<tr>
															<td >
																<img src=3D"http://cdn.mandrill.com/img/emails/mandrill-l=
ogo-36px.png" height=3D"36" width=3D"160" alt=3D"Mandrill" style=3D"borde=
r:0;min-height:auto;line-height:100%;outline:none;text-decoration:none;ma=
x-width:600px;display:block;">
															</td>
														</tr>
													</tbody>
												</table>
											</td>
										</tr>
									</tbody>
								</table>
							</td> =

						</tr>
						<tr>
							<td align=3D"center" valign=3D"top" style=3D"border-collapse:colla=
pse">
								<table border=3D"0" cellpadding=3D"20" cellspacing=3D"0" width=3D=
"100%" style=3D"border-collapse:collapse;background-color:#f1f1f2">
									<tbody>
										<tr>
											<td align=3D"center" valign=3D"top" style=3D"border-collapse:c=
ollapse">
												<table border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=
=3D"600" style=3D"border-collapse:collapse">
													<tbody>
														<tr>
															<td >
																<p><strong>We''ve received your request.</strong><br />You=
r ticket number is 78906.</p><p>If you have a Mandrill account, <em>pleas=
e ensure your username was included </em> along with <strong>detailed inf=
ormation</strong> about your request so we can respond as quickly as poss=
ible.</p><p>You can add additional comments by replying to this email.</p=
><p>In the meantime, search for common questions in our <a href=3D"http:/=
/help.mandrill.com">Knowledge Base</a>, check Mandrill''s <a href=3D"http:=
//status.mandrillapp.com">server status</a>, or review our <a href=3D"htt=
ps://mandrillapp.com/docs/">documentation</a>.</p><p></p><div style=3D"ma=
rgin-top: 25px" data-version=3D"2"><table width=3D"100%" cellpadding=3D"0=
" cellspacing=3D"0" border=3D"0"><tr><td width=3D"100%" style=3D"padding:=
 15px 0; border-top: 1px dotted #c5c5c5;">      <table width=3D"100%" cel=
lpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D" table-layout:fixe=
d;"><tr><td width=3D"100%" style=3D"padding: 0; margin: 0;" valign=3D"top=
">            <p >    =
          <strong>Paul DeBruicker</strong>             </p>            <p=
>              Jan=
 09 06:58 PM            </p>                                      <p >    Hi -   </p>  <p >    <br />  I''m trying to parse inbound =
emails to extract just the relevant parts of the reply.   With the defaul=
t settings for Inbound, it seems that your software is stripping out the =
line endings of the text body of the email.  Is that right, and if so is =
there a way to shut that off?  </p>  <p >    <br />  Thanks  </p>  <p >    <br />  Paul  </p>                                  </td=
>        </tr></table></td>  </tr></table></div>
															</td>
														</tr>
													</tbody>
												</table>
											</td>
										</tr>
									</tbody>
								</table> =

							</td>
						</tr>
						<tr>
							<td align=3D"center" valign=3D"top" style=3D"border-collapse:colla=
pse">
								<table border=3D"0" cellpadding=3D"20" cellspacing=3D"0" width=3D=
"100%" style=3D"border-collapse:collapse;background-color:#f1f1f2">
									<tbody>
										<tr>
											<td align=3D"center" valign=3D"top" style=3D"padding-bottom:40=
px;border-collapse:collapse">
												<table border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=
=3D"600" style=3D"border-collapse:collapse;border-top:1px solid #bbbbbb">=

													<tbody>
														<tr>
															<td valign=3D"top" align=3D"center" style=3D"padding-botto=
m:20px;border-collapse:collapse;color:#808184;font-family:Helvetica;font-=
size:12px;line-height:150%;text-align:center;padding-top:10px">

																=

																<a href=3D"http://mandrill.com" style=3D"color:#808184;fo=
nt-weight:normal;text-decoration:underline" target=3D"_blank">mandrill.co=
m</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href=3D"http://help.mandrill.com" style=3D=
"color:#808184;font-weight:normal;text-decoration:underline" target=3D"_b=
lank">Mandrill support</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href=3D"http://twit=
ter.com/mandrillapp" style=3D"color:#808184;font-weight:normal;text-decor=
ation:underline" target=3D"_blank">@MandrillApp</a>
															</td>
														</tr>
														<tr>
															<td valign=3D"top" align=3D"center" style=3D"padding-botto=
m:20px;border-collapse:collapse;color:#808184;font-family:Helvetica;font-=
size:12px;line-height:150%;text-align:center;padding-top:10px">

																&copy; 2014 All rights reserved.<br>
																Mandrill&reg; is a registered trademark of The Rocket Sci=
ence Group<br>
																=

																512 Means Street Suite 404 Atlanta, GA 30318
															</td>
														</tr>
													</tbody>
												</table>
											</td>
										</tr>
									</tbody>
								</table>
							</td>
						</tr>
					</tbody>
				</table>
			</td>
		</tr>
	</tbody>
</table>
</center>
<span >Message-Id:MTNPHCZJ_54b06b36abdfc_2a253f816=
90cd40425822b_sprut</span><span >Ticket-Id:78906</span></body>
</html>=

----==_mimepart_54b06b36ce026_2a253f81690cd404258493--
'